export const stories = [
  {
    profileImg: "/stories/profile-1.png",
    profileName: "Plated Stories",
    title: ["We craft stories", "that people", "can taste"],
    linkLabel: "View Case Study",
    linkSrc: "/sample-project",
    storyImg: "/stories/story-1.jpg",
  },
  {
    profileImg: "/stories/profile-2.png",
    profileName: "Content Curation",
    title: ["Content built", "on storytelling,", "strategy and craft"],
    linkLabel: "View Case Study",
    linkSrc: "/sample-project",
    storyImg: "/stories/story-2.jpg",
  },
  {
    profileImg: "/stories/profile-3.png",
    profileName: "Creative Direction",
    title: ["Aesthetics,", "storytelling and", "brand growth"],
    linkLabel: "View Case Study",
    linkSrc: "/sample-project",
    storyImg: "/stories/story-3.jpg",
  },
  {
    profileImg: "/stories/profile-4.png",
    profileName: "Shooting",
    title: ["Premium production", "for food and", "lifestyle brands"],
    linkLabel: "View Case Study",
    linkSrc: "/sample-project",
    storyImg: "/stories/story-4.jpg",
  },
  {
    profileImg: "/stories/profile-2.png",
    profileName: "Editing",
    title: ["Finalized content", "delivered in", "5 to 7 days"],
    linkLabel: "View Case Study",
    linkSrc: "/sample-project",
    storyImg: "/stories/story-5.jpg",
  },
  {
    profileImg: "/stories/profile-4.png",
    profileName: "Social Management",
    title: ["End-to-end support", "from planning", "to publishing"],
    linkLabel: "View Case Study",
    linkSrc: "/sample-project",
    storyImg: "/stories/story-6.jpg",
  },
];
